import { writable } from 'svelte/store';

// Configuration store - can be updated from UI controls
export const vizConfig = writable({
    adrRange: 100,
    pulseThreshold: 0.5,
    pulseScale: 5,
    maxMarkerDecay: 10,
    flashThreshold: 2,
    adrProximityThreshold: 10,
    frequencyMode: 'normal',
    priceBucketSize: 0.5,
    showMaxMarker: true,
    showVolatilityOrb: true,
    volatilityColorMode: 'intensity',
    volatilityOrbBaseWidth: 70,
    volatilityOrbInvertBrightness: false,
    showMarketProfile: true,
    showFlash: false,
    flashIntensity: 0.3,
    showOrbFlash: false,
    orbFlashThreshold: 2,
    orbFlashIntensity: 0.8,
    distributionDepthMode: 'all',
    distributionPercentage: 50,
    marketProfileView: 'bars',
    priceFontSize: 50,
    priceFontWeight: '600',
    priceHorizontalOffset: 14,
    priceFloatWidth: 50,
    priceFloatHeight: 1,
    priceFloatXOffset: 20,
    bigFigureFontSizeRatio: 1.2,
    pipFontSizeRatio: 1.1,
    pipetteFontSizeRatio: 0.8,
    showPriceBoundingBox: false,
    showPriceBackground: false,
    priceDisplayPadding: 4,
    priceStaticColor: false,
    priceUpColor: '#3b82f6',
    priceDownColor: '#ef4444',
    visualizationsContentWidth: 220,
    centralAxisXPosition: 170,
    meterHeight: 120,
    centralMeterFixedThickness: 8,
    showPipetteDigit: false,
    showSingleSidedProfile: false,
    singleSidedProfileSide: 'right',
});
