language: "javascript"
name: "NeuroSense FX"
project_root: "/workspaces/c"

language_servers:
  javascript:
    command: "typescript-language-server"
    args: ["--stdio"]
  typescript:
    command: "typescript-language-server"
    args: ["--stdio"]
    
modes:
  - planning
  - editing
  - interactive
  
contexts:
  - ide-assistant
  
tools:
  enabled:
    - find_symbols
    - find_references
    - find_definitions
    - edit_symbol
    - create_file
    - read_file
    - list_files
    - search_files
    - replace_in_file
    - memory_tools
    - config_tools
    
  excluded:
    - execute_shell_command
    - git_operations

# NeuroSense FX specific configuration
neurosense_fx:
  architecture:
    - two_server_pattern: true
    - frontend_server: "vite:5173"
    - backend_server: "node:8080"
  
  key_directories:
    - src/components/viz
    - src/stores
    - src/workers
    - services/tick-backend
    - libs/cTrader-Layer
    - memory-bank
  
  performance_requirements:
    - target_fps: 60
    - max_displays: 20
    - memory_limit: "500MB"
    - cpu_limit: "50%"
